### ISSUE TITLE
namespace confusion - not an official ring lib

### ISSUE THREAD

**Issue by mobileink** [metosin/ring-http-response#10]
Hi,

Using namespaces like `ring.util.http-response` is confusing.  It makes it look like this is an official ring lib, leading the unsuspecting reader (i.e. me) to search https://github.com/ring-clojure for documentation.

Not a huge issue, but annoying enough that I cloned the repo and changed the namespaces to start with `ringx` instead of `ring`.  If you're open to this change let me know and I'll send a pull request.  They're at https://github.com/mobileink/ringx-http-response

Thanks,

Gregg

**Comment by mobileink** [comment]
PS. my changes are in the `ringx` branch.

**Comment by Deraen** [comment]
It's common practice to name libraries extending ring functionality this way.

I.e. https://github.com/ngrunwald/ring-middleware-format
Also most of current official ring libraries didn't start as official ring libs, but were moved there once they were commonly used.
