### ISSUE TITLE
Allow passing a URL to ring.util.http-response/created

### ISSUE THREAD

**Issue by mkaschenko** [metosin/ring-http-response#12]
>10.2.2 201 Created
The request has been fulfilled and resulted in a new resource being created. The newly created resource can be referenced by the URI(s) returned in the entity of the response, with the most specific URI for the resource given by a Location header field. The response SHOULD include an entity containing a list of resource characteristics and location(s) from which the user or user agent can choose the one most appropriate.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/util/response.clj#L37

**Comment by ikitommi** [comment]
Fixed in `[metosin/ring-http-response "0.8.0"]`, works just like with Ring. Thanks for reporting!
