### ISSUE TITLE
0.8.0 jar not including changes from 0d73bbaf8c80b45e5de28762a30a83281bffab9f

### ISSUE THREAD

**Issue by sickill** [metosin/ring-http-response#14]
I'm experiencing some weird bug with `(created ...)`. I have upgraded from 0.6.5 to 0.8.0 and I'm getting this on my dev environment:

```
user=> (filter #(re-find #"response" (str %)) (seq (.getURLs (java.lang.ClassLoader/getSystemClassLoader))))
(#object[java.net.URL 0x438dcd91 "file:/home/vagrant/.m2/repository/metosin/ring-http-response/0.8.0/ring-http-response-0.8.0.jar"])
user=> (ring.util.http-response/created "aa" {:lol 1})
ArityException Wrong number of args (2) passed to: http-response/created  clojure.lang.AFn.throwArity (AFn.java:429)
```

However, it's fine (2 arity fn works) on my testing server. I upgraded to 0.8.0 few days ago, and leiningen probably downloaded it in my dev env about 1-2 days before it did the same on the testing server.

**Comment by sickill** [comment]
Hold on, this looks like some leiningen compilation class caching issue...

**Comment by sickill** [comment]
That was indeed some leiningen caching thing. Sorry about the noise!

**Comment by ikitommi** [comment]
no prob. Glad it got resolved.
