### ISSUE TITLE
Inconsistent :body defaults in ring.util.http-response

### ISSUE THREAD

**Issue by Elknar** [metosin/ring-http-response#19]
Some responses default to a `nil` body, while others use an empty string.

For example, compare `ok` and `no-content`.

**Comment by leblowl** [comment]
I was thinking the same thing, it doesn't look like nil vs empty string has any obvious effect on the response, I get content-length: 0 for both. I suggest we unify it. Ring uses empty strings here: https://github.com/ring-clojure/ring/blob/736394806167cb2af87716655f73da9f8fbd0226/ring-core/src/ring/util/response.clj#L20-L36

**Comment by Deraen** [comment]
Empty string is used for responses which will never have a body, i.e. non-entity response types like informational (100-199) or redirection (300-399). This is to match to the linked Ring `redirect` and `redirect-after-post` functions.

**Comment by leblowl** [comment]
Awesome, thanks for the info
