### ISSUE TITLE
Suggestion: Allow passing headers to responses

### ISSUE THREAD

**Issue by leblowl** [metosin/ring-http-response#20]
I know there isn't much difference between `{:status 200 :headers {} :body {}}` and `(ok {} {})` but I think it would be nice to allow headers on the HTTP response helper functions. We can overload all the response helpers with one more alternative.

**Comment by leblowl** [comment]
For example: 
```clojure
(defn ok
  "200 OK (Success)
  OK"
  ([] (ok {} nil))
  ([body] (ok {} body))
  ([headers body]
   {:status 200
    :headers headers
    :body body}))
```

**Comment by Deraen** [comment]
No, I don't like this.

Ring already provides loads of functions to modify response map headers and they are easy to use with `->`, e.g.

```clj
(-> (ok {})
    (content-type "application/json+foo")
    (header "X-Token" "123"))
```

And these functions are already exposed (with import-vars) from `ring.util.http-response` namespace.

**Comment by leblowl** [comment]
I see. Makes sense. Thanks, Ill try to use these functions instead.
