### ISSUE TITLE
Headers should be lower-cased

### ISSUE THREAD

**Issue by opqdonut** [metosin/ring-http-response#35]
Currently, ring-http-response uses header names like `"Content-Type"`. However, the ring spec defines that headers should be lower-cased: https://github.com/ring-clojure/ring/blob/master/SPEC.md#headers-1

This is important in case there are middleware in the pipeline that expect to be able to parse eg. the content-type header, and are looking for it under the `"content-type"` name.

I think we should label this fix as a breaking change, since somebody might've been relying on the exact naming of the headers.

**Comment by opqdonut** [comment]
Interesting, the `"Content-Type"` header comes directly from ring.util.response:

https://github.com/ring-clojure/ring/blob/f7dfe7c9b98c335e4573e61d94c523d5df9a6667/ring-core/src/ring/util/response.clj#L184

**Comment by opqdonut** [comment]
Let's keep this open while the original ring bug is open.

**Comment by weavejester** [comment]
Thanks for discovering this bug. The error was in the spec. It looks like when I converted it to markdown the "lowercased" adjective was added to the response header definition erroneously. I've since fixed this and the spec should now be correct.

**Comment by opqdonut** [comment]
Yeah, thanks for the clarification!

**Comment by opqdonut** [comment]
The original fix was reverted in #37
