### ISSUE TITLE
NPE during import

### ISSUE THREAD

**Issue by Otann** [metosin/ring-http-response#8]
Hi guys!

Trying to use your great library, added dependency to `project.clj` and then got following in repl:

```
main=> (require '[ring.util.http-response :refer :all])
CompilerException java.lang.NullPointerException, compiling:(ring/util/http_response.clj:1066:21) 
```

Am I doing something wrong?

**Comment by Deraen** [comment]
I can't reproduce this. Might be caused by some incompatibilities with other dependencies?

**Comment by Otann** [comment]
Probably so, can't reproduce it either
